[TypeScript & Module Typing] 동키콩(주동혁) 미션 제출합니다.
woowacourse/ts-module pull request #18
Opened 2022-09-27 13:39 UTC by JUDONGHYEOK

## 🔥 팀 미션 적용 결과

본 미션을 수행하며 경험, 영감, 학습한 내용을 팀 미션에 전파해주세요.

- [x] 실제 코드 반영 후 팀 프로젝트에서 타입 테스트 진행
- [x] 자주 사용되는 타입을 유틸로 출시하여 분리

### 🤗[Sokdak-Utils](https://www.npmjs.com/package/sokdak-util-types)
## ✅ 요구사항 구현 확인

> 필히 테스트 & 타입이 포함

### DOM 유틸

- [x] innerHTML()
- [x] show()
- [x] hidden()
- [x] addEvent()

### 유틸

- [x] fetch()
- [x] isNull()
- [x] isNil()
- [x] isNumber()
- [x] isFunction()
- [x] shuffle()
- [x] pick()
- [x] omit()
- [x] memoize()
- [x] debounce()
- [x] throttle()
- [x] clickOutside()

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/
TaeTae 작성중입니다!!

2022-09-28 07:57 UTC, nan-noo requested changes
- 테스트와 타입 선언 부에 코멘트 달았습니다!
- 아래 타입이 어떤 상황에서 쓰이는지 설명해주세요!! 궁금하네요 :D 
```ts
export type StateAndAction<T, K extends string> = {
  [P in K]: T;
} & {
  [P in `set${Capitalize<K>}`]: Dispatch<SetStateAction<T>>;
};
```

> 미션 진행하면서 각종 모듈 들에 대해서 알게 되었습니다! namespace와 module, 모듈모드와 스크립트 모드를 나눠서 생각하고 모듈에 대한 고민을 처음 해봤던 것 같습니다! 태태는 어떤식으로 모듈을 분리하고 선언하였는지 궁금하네요!!😮

오 모듈 모드와 스크립트 모드가 뭔가요?? 저는 이번에는 요구사항만 했지만..! 저는 보통 기능이나 도메인 단위로 모듈로 만듭니다!

> 이번 미션을 진행하면서 Parmeters와 Capitalize등의 유틸리티 타입들을 활용하면서 제가 몰랐던 유틸리티 타입들에 대해서 다시 한 번 정리하는 시간이 되었습니다!
> 이번 미션에서 Iterable과 같은 기본 타입들을 활용해 보았습니다. 생각보다 많은 타입들이 기본으로 제공되고 있더군요!!

저도 동키콩 코드를 보고 Parameters 타입이 있는 걸 알았어요!! :D 이 밖에도 더 많더라구요 ReturnType이라든지.. 뭔가 유틸 타입을 정의하기 전에 내장된 타입이 있는지 확인하고 써야 할 것 같아요.

2022-09-28 07:57 UTC, nan-noo commented on package.json
> +    "@babel/preset-env": "^7.19.1",
바벨은 왜 필요한가요??

2022-09-28 07:57 UTC, nan-noo commented on src/index.ts
> +    result.sort(() => Math.random() - 0.5);
이게 완벽한 shuffle은 아니라고 하네요!

- https://dev.to/codebubb/how-to-shuffle-an-array-in-javascript-2ikj
- https://stackoverflow.com/questions/962802/is-it-correct-to-use-javascript-array-sort-method-for-shuffling
- http://www.robweir.com/blog/2010/02/microsoft-random-browser-ballot.html

2022-09-28 07:57 UTC, nan-noo commented on src/index.ts
> +  export function shuffle(input: object | Iterable<unknown>): unknown[] {
array말고 object도 받을 수 있게 했군요

2022-09-28 07:57 UTC, nan-noo commented on src/index.ts
> +    K extends string[] | string[][]
타입만 보면 K가 T의 key가 아니어도 타입 에러가 안 뜰 것 같은데, 코드 상에서 예외 처리한 부분이 안 보여서 질문합니다!

2022-09-28 07:57 UTC, nan-noo commented on src/index.ts
> +  >(obj: T, ...target: K): Partial<T> {
리턴 타입을 더 좁힐 수 있지 않을까요?
예를 들어, 
T = {a: number; b: number}
K = ["a"] 일 때
원하는 리턴 타입은 {a: number} 일텐데, 현재 타입만 보면 {a?: number; b?: number}라서 더 범위가 넓습니다!

2022-09-28 07:57 UTC, nan-noo commented on src/index.ts
> +      }
런타임 예외처리도 하셨군요!

2022-09-28 07:57 UTC, nan-noo commented on tsconfig.json
> +    "module": "commonjs" /* Specify what module code is generated. */,
commonjs로 한 이유가 무엇인가요?

2022-09-28 07:57 UTC, nan-noo commented on tsconfig.json
> +    // "incremental": true,                              /* Enable incremental compilation */
주석을 남겨놓은 이유가 무엇인가요??

2022-09-28 07:57 UTC, nan-noo commented on __tests__/api.test.ts
> +test('fetch 테스트', () => {});
유틸 함수 테스트가 몇가지 빠진 것 같아요!

shuffle, pick, omit, memoize는 테스트해도 좋을 것 같은데 어떻게 생각하나요?

2022-09-28 07:57 UTC, nan-noo commented on __tests__/type.test.ts
> +  });
jest랑 tsd를 같이 쓰셨군요! 맞나요?? 같이 사용한 이유가 무엇인가요?

2022-09-28 07:57 UTC, nan-noo commented on __tests__/type.test.ts
> +  expectType<Array<unknown>>(_.shuffle(() => {}));
unknown은 너무 광범위하지 않을까요??

2022-09-29 02:08 UTC, JUDONGHYEOK commented on tsconfig.json
> +    "module": "commonjs" /* Specify what module code is generated. */,
사실 tsc init 하면 나오는 속성 거의 그대로 사용하였는데요. 큰 뜻은 없고 es module을 사용하기엔 구동환경이 특정 지어지지 않았기 때문에 좀 더 범용성 있는 commonjs를 사용하는게 합리적일거라고 생각했습니다!

2022-09-29 02:09 UTC, JUDONGHYEOK commented on tsconfig.json
> +    // "incremental": true,                              /* Enable incremental compilation */
이건 사실ㅎㅎㅎ 나중에 추가할 속성이 필요하다면 보고 키워드를 검색하기 위해 남겨두었는데요.  삭제하겠습니다...🫠

2022-09-29 02:11 UTC, JUDONGHYEOK commented on package.json
> +    "@babel/preset-env": "^7.19.1",
하핳 jest설정 하다가 집어넣은 것 같은데 필요가 없네요ㅎㅎ 삭제해주었습니다!!
[7c6d5f2](https://github.com/woowacourse/ts-module/pull/18/commits/7c6d5f28403978c5438e649d5b132fdac311ee89)

2022-09-29 02:13 UTC, JUDONGHYEOK commented on src/index.ts
> +    result.sort(() => Math.random() - 0.5);
lodash 에서  Fisher-Yates 알고리즘을 사용한다고는 보았는데 이해가 가질 않아 제 마음대로 구현했었는데요. 보내주신 링크를 보니 이해가 쏙쏙 되는 군요 감사함다 태태
[5b9d97d](https://github.com/woowacourse/ts-module/pull/18/commits/5b9d97dc922b9a3d6f1009126fd01707f1706f4e)

2022-09-29 02:14 UTC, JUDONGHYEOK commented on src/index.ts
> +  export function shuffle(input: object | Iterable<unknown>): unknown[] {
넵 lodash에서 해보니 object도 다 들어가더군요.. 최대한 똑같이 구현하려고 object도 받을 수 있게끔 타입을 지정해주었습니다!

2022-09-29 02:16 UTC, JUDONGHYEOK commented on src/index.ts
> +    K extends string[] | string[][]
오호 예리한 지적 감사합니다 처음에 생각했을 때는 이걸 타입스크립트에서 처리하는 게 맞나 라는 생각이 들어서 위처럼 구현을 했었는데요 생각해보니 pick은 유틸 함수이고 휴먼에러를 방지하기 위해 타입스크립트에서 사용했다면 개발자가 불필요한 인자를 전달하는 것을 방지하고자 사용할 수 있을 것 같네요!! key가 아닌 파라미터를 전달하면 아무 일도 발생하지 않으니깐요! 감사합니다 태태 바로 수정하겠습니다!
[5562730](https://github.com/woowacourse/ts-module/pull/18/commits/5562730d629e5ed4a2451ac90aca962a4abc1706)

2022-09-29 02:17 UTC, JUDONGHYEOK commented on src/index.ts
> +      }
넵ㅎㅎ 아무래도 dom을 다루는 유틸함수다보니 런타임 에러가 잦지 않을까 싶어서 해당 처리도 해주었어요! 😃

2022-09-29 02:17 UTC, JUDONGHYEOK commented on __tests__/api.test.ts
> +test('fetch 테스트', () => {});
유틸 함수에 대한 테스트는 util.test.ts에 있습니다!! 혹시 테스트 케이스가 부족하다고 말씀하시는 걸까요???

2022-09-29 02:18 UTC, JUDONGHYEOK commented on __tests__/type.test.ts
> +  });
넵 큰 이유는 없고 jest 명령어로 타입 테스트와 동작 테스트를 동시에 진행하고 또 타입테스트에 대한 설명을 명시하기 위해 사용했습니다!

2022-09-29 02:18 UTC, JUDONGHYEOK commented on __tests__/type.test.ts
> +  expectType<Array<unknown>>(_.shuffle(() => {}));
오호 동의 합니다! 거의 의미가 없는 테스트였네요 number로 교체해 주었어요!!

2022-09-29 02:19 UTC, JUDONGHYEOK commented on src/index.ts
> +  >(obj: T, ...target: K): Partial<T> {
오호 범위를 너무 넓게 잡았네요 예리한 지적 감사합니다 이역시 위 커밋에서 수정하였습니다!

2022-09-29 02:29 UTC, JUDONGHYEOK commented
> 아래 타입이 어떤 상황에서 쓰이는지 설명해주세요!! 궁금하네요 :D

저희 코드를 보시면 
```typescript
interface Props{
    nickname:string;
    setNickname: Dispatch<SetStateAction<string>>;
}
```
와 같은 인터페이스가 많이 사용되더라구요. 이러한 인터페이스의 중복을 조금이나마 줄일 수 있지 않을까? 싶어서 해당 타입을 만들어봤어요...ㅎㅎㅎ

> 오 모듈 모드와 스크립트 모드가 뭔가요??

모듈 모드와 스크립트는 사실 별 내용은 아닌데요. 모듈에 대한 키워드를 찾다보니 나오더라구요!! 타입스크립트는 import와 export를 포함하면 모듈모드로 그렇지 않으면 스크립트 모드로 타입스크립트 파일을 파싱한다고 해요! 스크립트 모드에서는 최상위 수준으로 선언한 모든 변수는 명시적으로 임포트하지 않아도 다른 파일에서 사용할 수 있어서 제 생각에는 대부분의 상황에서 파일간 캡슐화가 힘들고 휴먼에러가 발생할 확률이 높을 것 같아요! 실제 거의 언제나 모듈모드를 사용한다고 하네요!!

태태 꼼꼼하게 리뷰해주셔서 감사해요!! 태태 덕분에 tsconfig와 package.json도 다시 한 번 들여다 보게 되었고 타입을 좁히는 연습도 할 수 있었습니다!! 혹시 더 부족하다고 싶은 사항 있으시면 마음껏 리뷰 부탁드려요~~🤗

2022-09-29 03:58 UTC, nan-noo approved these changes
빠르게 반영했군요!

2022-09-29 03:58 UTC, nan-noo commented on __tests__/api.test.ts
> +test('fetch 테스트', () => {});
앗 못봤네요 :D

2022-09-29 04:06 UTC, merged