[TypeScript & Module Typing] 무비(변영화) 미션 제출합니다.
woowacourse/ts-module pull request #20
Opened 2022-09-27 13:40 UTC by byhhh2

>
> 추후...작성하겠습니다 😴
>

## 🔥 팀 미션 적용 결과

본 미션을 수행하며 경험, 영감, 학습한 내용을 팀 미션에 전파해주세요.

- [ ] 실제 코드 반영 후 팀 프로젝트에서 타입 테스트 진행
- [ ] 자주 사용되는 타입을 유틸로 출시하여 분리

## ✅ 요구사항 구현 확인

> 필히 테스트 & 타입이 포함

### DOM 유틸

- [ ] innerHTML()
- [ ] show()
- [ ] hidden()
- [ ] addEvent()

### 유틸

- [ ] fetch()
- [ ] isNull()
- [ ] isNil()
- [ ] isNumber()
- [ ] isFunction()
- [ ] shuffle()
- [ ] pick()
- [ ] omit()
- [ ] memoize()
- [ ] debounce()
- [ ] throttle()
- [ ] clickOutside()

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/

2022-09-28 17:42 UTC, jin7969 requested changes
안녕하세요 무비~~~ 리뷰어를 맡게 된 "안" 입니다 ㅎㅎ
작은 강의실에서 봤는데, 엄청 집중하시더라구요! 👍
테스트와 주석까지.. 열심히 하신게 느껴지네요 ㅎㅎ
열심히 하는 모습 본 받겠습니다 하하;;
몇가지 코멘트 남겼습니다.

## 🧐 공유
> 포코는 왜 module 키워드를 썼을까요?

저는 이렇게 까지 생각을 안해봤는데... 무비 덕분에 namespace 배워갑니다 ㅎ

> 도대체 미션을 어떻게 진행해야되는 것일까요?

저도 처음에 어떻게 해야 하는지 도저히 모르겠더라구요, ㅠㅠ 이리저리 물어보러 다녔던거 같아요;;

1. index.ts에서 function과 module에 declare를 붙인다. (declare를 붙이므로써 typescript 컴파일러에게 타입 정보알린다. 저는 그냥 타입으로 만들어준다. - js로 컴파일되는 것을 막는다. 라고 생각했어요.)
2. 함수명과 함수 구현을 살짝 훔쳐보면서 타입을 추론하며 선언부에 채워준다.
3. tsd를 통해 type test를 진행한다.
4. declare를 떼버리고 index.ts에서 구현을 진행한다.

위 부분에 대해서는 저도 같은 생각입니다 ㅎ

2022-09-28 17:42 UTC, jin7969 commented on __tests__/api.test.ts
> +    const divElement = document.createElement('div');
공통된 부분은 위에 선언하고 사용해도 되지 않나요??
```
describe("Selector 및 메서드 동작 확인", () => {
  const divElement = document.createElement("div");
  ...
  test("Selector 동작 확인", () => {
  ...
  });
```

2022-09-28 17:42 UTC, jin7969 commented on __tests__/api.test.ts
> +});
테스트를 열심히 구현 하셨군요! 👍 역시 무비~~

2022-09-28 17:42 UTC, jin7969 commented on jest.config.ts
> +  testPathIgnorePatterns: ['<rootDir>/__tests__/type.test.ts'],
잘 몰라서 그러는데.. 두가지 왜 사용했는지 간략하게 설명 부탁드려요 ㅎㅎ
`transformIgnorePatterns, testPathIgnorePatterns`

2022-09-28 17:42 UTC, jin7969 commented on src/index.ts
> +   */
주석을 달아주니 이해하는데 도움이 되네요 ㅎㅎ 👏

2022-09-28 17:42 UTC, jin7969 commented on src/index.ts
> +  }
fetch 부분은 조금 더 명확하게 할 수 있을 거 같아요;; 적용안하고 알고만 넘어가도 됩니당 ㅎㅎ

2022-09-28 17:42 UTC, jin7969 commented on src/index.ts
> +    return array.sort(() => Math.random() - 0.5);
간단한 방법도 있군요! ㅎ

2022-09-28 17:42 UTC, jin7969 commented on src/index.ts
> +    object: T,
Record<> 를 사용하면 조금 더 유용하지 않을까요?

2022-09-29 11:23 UTC, byhhh2 commented on __tests__/api.test.ts
> +    const divElement = document.createElement('div');
맞습니다 ㅎㅎ 
타입을 중점적으로 생각하는 미션이라 테스트 중복 코드는 신경쓰지 않았어요!!

2022-09-29 11:24 UTC, byhhh2 commented on jest.config.ts
> +  testPathIgnorePatterns: ['<rootDir>/__tests__/type.test.ts'],
만나뵙고 설명드리죠. 🤩

2022-09-29 11:24 UTC, byhhh2 commented on src/index.ts
> +  }
구현은 간단하게 진행했습니다 ㅎㅎ

2022-09-29 11:34 UTC, byhhh2 commented on src/index.ts
> +    object: T,
앨버 크루를 리뷰하면서 더 깔끔한~ 방법을 발견해서 수정했는데 리뷰어님이 보시긴 어떤가요? ㅎㅎ 

[`cf523bd`](https://github.com/woowacourse/ts-module/pull/20/commits/cf523bdfe076afe2711afb2c9cd42ad9e8a7c241)

2022-09-29 11:46 UTC, merged