[TypeScript & Module Typing] 온스타(온승찬) 미션 제출합니다.
woowacourse/ts-module pull request #22
Opened 2022-09-27 13:46 UTC by cks3066

## 🔥 팀 미션 적용 결과

본 미션을 수행하며 경험, 영감, 학습한 내용을 팀 미션에 전파해주세요.

- [ ] 실제 코드 반영 후 팀 프로젝트에서 타입 테스트 진행
- [x] 자주 사용되는 타입을 유틸로 출시하여 분리

[npm 배포 주소](https://www.npmjs.com/package/gongcheck-util-types)
[Git 저장소](https://github.com/gong-check/gongcheck-util-types)

- 유틸 타입 라이브러리의 경우는 index.d.ts 를 직정 작성해서 배포하면 될 것 같아서, index.d.ts만 가지고있는데, 앨버는 어떻게 진행하셨나요?

## ✅ 요구사항 구현 확인

> 필히 테스트 & 타입이 포함

### DOM 유틸

- [x] innerHTML()
- [x] show()
- [x] hidden()
- [x] addEvent()

### 유틸

- [ ] fetch()
- [x] isNull()
- [x] isNil()
- [x] isNumber()
- [x] isFunction()
- [x] shuffle()
- [x] pick()
- [x] omit()
- [x] memoize()
- [x] debounce()
- [x] throttle()
- [ ] clickOutside()

---
반갑습니다!! 앨버!!! 🫶

이번 미션을 진행하면서 여러 라이브러리의 깃허브을 구경하고 어떤식으로 타입스크립트를 작성하고 테스트를하는지 많이 봤습니다..!

이전까지는 항상 빨간줄 지우기만 하면서 타입체크의 기능만 사용했었는데, 
이번 미션에서는 런타임의 타입체크, 사용자를 위한 타입선언을 주로 생각하면서 미션을 진행했습니다.

내가 만든 함수를 다른 프로젝트에 적용해서 사용해보았는데, 작성한 타입스크립트가 해당 함수의 사용법에 대해서 안내를 해주는 것을 보고, 왜 라이브러리들에 많은 사람들이 타입스크립트를 요구하는지 느꼈습니다..!

---
## ✋ 궁금한 점
### 모든 타입 테스트
이번 미션에서 test를 진행할때 모든 타입에 대해 감사를 해야겠다라는 생각을 해 allType라는 객체에 proxy를 제외한 모든 타입을 선언하고 테스트에서 순회를 하면서 사용을 했는데, 하고보니 이럴 필요가 있나라는 생각도 들기도하는데, 앨버는 어떻게 보시나요..?

### tsd
함수 구현 내부에서 타입가드겸 맞지 않는 타입이 들어왔을 때, throw문으로 에러를 띄울 수 있도록 해놓았는데, 이 경우 tsd 없이도 어느정도 타입 테스트가 진행이 가능했던 것 같습니다. tsd에 대한 필요성을 미션을 진행하면서 잘 느끼지 못했는데, 앨버에게 tsd를 사용한 경험은 어땠나요?

---
## 🧐 공유

### tsc(ts-loader) vs babel(babel-loader) vs esbuild(esbuild-loader)
이번 프로젝트에서 번들까지는 필요없겠다 생각해서, tsc 명령어로만 빌드하였습니다.
babel, tsc, esbuild의 트랜스파일링 과정이 어떻게 다른지 알아볼 기회가 생겨서 알아보았습니다.

tsconfig.json의 관점에서 해석하면 차이점을 인지하기가 보다 쉬운데,
tsconfig.json는 tsc 명령어로 컴파일할때 컴파일에 대한 옵션을 제공하며, vsc의 내장 타입 체커인 tsserver도 이 tsconfig의 옵션을 확인하여 타입체크를 진행합니다. 

tsc 명령어로 트랜스파일링을 진행할때 직접 tsconfig 파일을 지정하지 않으면 프로젝트 디렉토리를 순회하면서 tsconfig.json 파일을 찾고 컴파일 옵션에 따라 트랜스파일을 진행합니다. 
(* 직접 지정할 수 있다는 것은 tsconfig 파일이 경우에 따라 여러개 일 수 있다는 뜻)
(* tsc와 함께 옵션을 직접 지정할 수 있는데, 이때 직접 커맨드에 지정한 옵션이 우선시 됨)
(* tsc index.ts 처럼 파일을 직접 지정할 경우, tsconfig.json의 옵션은 무시되고 기본 옵션으로 적용됨)

이때 'declaration' 옵션을 활성화 시키면, 
컴파일된 파일들이 다른 타입스크립트 프로젝트에서도 타입추론이 가능하도록 해주는 d.ts 파일을 제공할 수 있는데,
이는 tsc 명령어로 트랜스파일링할 경우에만 가능합니다.

또한 tsc 명령어는 컴파일 과정에서 타입체크를 기본적으로 진행합니다.

`babel`
babel로 트랜스파일할 경우 babel은 tsconfig.json의 옵션을 확인하지 않고 대신 babel-prest-typescipt의 기본 옵션을 사용합니다. 
(babel로 빌드할 때 tsconfig.json에 컴파일 옵션을 아무리 적어도 의미가 없음)
tsc의 트랜스파일과정과는 다르기때문에, 타입체크를 진행하지도 않고, declaration 옵션으로 d.ts 파일을 생성할 수 없습니다.
단 이 점 덕분에, tsc의 트랜스파일링보다는 훨씬 빠르게 작동합니다.

`esbuild`
esbuild는 다른 컴파일러보다 go 언어, 병렬처리, 타입체크X 등의 이유로 더 빨리 동작하는데, esbuild는 babel과 다르게 tsc 명령어와 관련이 없지만 tsconfig의 옵션을 참고합니다. tsconfig를 기반으로 트랜스파일을 진행하는 것은 아니고, jsxFactory, jsxFragmentFactory, useDefundeForClassFields, importsNotUsedAsValues 의 옵션만 부분적으로 확인하고 적용합니다.
다른 컴파일 옵션은 esbuild의 옵션을 따르기 때문에 declatation 옵션을 사용할 수 없고, esbuild의 경우도 d.ts 파일을 생성할 수 없습니다.

(babel, esbuild 로 컴파일 하며, d.ts 를 제공하고싶은 경우 tsc --emitDeclarationOnly 같은 커맨드를 포함시켜야함)

---
공유에 적은 내용은 복습할 겸 적었습니다..! 
리뷰 진행하시다가 코드에 의아하신 부분 있으면 댓글, dm 어떤 부분이든 상관없으니 언제든지 물어봐주세요!
잘부탁드립니다 👍

2022-09-28 10:29 UTC, al-bur commented
사실, 제가 생각했을 때 테스트라는 것은(TDD가 아니라는 가정) 여러 가지 이유로 진행된다고 생각합니다.
첫 번째는, 검증을 하고자 하는 것(함수, 로직, 타입등)이 복잡해서 예상하기 힘든 상황들을 꼼꼼하게 체크하기 위해서!
ex) 유틸 타입를 테스트하기 위해 거의 모든 경우의 수(input + output)에 대한 테스트 코드를 작성
두 번째는, 리팩토링 과정에서 실수를 방지하고, 리팩토링 속도를 올리기 위해서!
ex) 복잡한 유틸 타입에 대한 리팩토링을 진행할 때마다, 모든 경우의 수를 일일이 체크하기란 쉽지 않습니다. 휴먼 에러가 발생하게 되면 이전에 동작했던 것들도 동작하지 않을 가능성이 큽니다. 그래서 테스트를 통해서 이러한 위험들을 감소시키면서 리팩토링 속도를 올릴 수 있을 것 같습니다.

결론을 말씀드리면, 단순한 타입에 대한 테스트에 대해서는 의문이 들고, 복잡한 타입에 대해서는 테스트를 해주는 것이 안전한 서비스를 만들 수 있는 요소가 될 수 있을 것 같습니다.

2022-09-28 10:52 UTC, al-bur commented
> 함수 구현 내부에서 타입가드겸 맞지 않는 타입이 들어왔을 때, throw문으로 에러를 띄울 수 있도록 해놓았는데, 이 경우 tsd 없이도 어느정도 타입 테스트가 진행이 가능했던 것 같습니다. tsd에 대한 필요성을 미션을 진행하면서 잘 느끼지 못했는데, 앨버에게 tsd를 사용한 경험은 어땠나요?

`함수 구현 내부에서 타입가드겸 맞지 않는 타입이 들어왔을 때, throw문으로 에러를 띄울 수 있도록 해놓았는데, 이 경우 tsd 없이도 어느정도 타입 테스트가 진행이 가능했던 것 같습니다.` 에 대한 혹시 예시를 알려주실 수 있으신가요?!

질문에 대한 답변을 드리는데 더 도움이 될 것 같아서요!!

### tsd 사용 경험
일단은, 이번에 제가 tsd를 사용한 경험에 대해서 말씀드릴게요

결론부터 말씀드리면, `복잡한 타입을 만들 때는 tsd를 사용해도 좋겠다`입니다.

저는 다음과 같은 flow의 tdd 방식을 사용해 타입을 정의해주었습니다.
타입에 대한 테스트 작성(테스트 실패) => 테스트를 통과하기 위한 타입 선언(테스트 성공) => 로직 구현 및 타입 적용

이번 미션에서 pick, omit등과 같이 조금 복잡한 유틸 타입을 처음부터 만드는 것이 조금 막막했었습니다. 근데, tdd 방식을 통해 미리 타입의 input과 output에 대한 테스트 코드들을 작성해보고 하나씩 테스트들을 통과시키기 위해 타입을 작성하다보니 어느덧 원하던 복잡한 유틸 함수가 만들어져있었습니다. 이렇게 복잡한 타입을 만드는 데, tsd를 통한 tdd 방식은 꽤 괜찮다고 생각합니다. (단, tdd가 아닐 때는 잘 모르겠네요. 온스타는 어땠나요? 복잡한 타입을 만드는 데 테스트가 도움이 됐나요??)

지금 생각해보니, tsd를 통해 타입에 대해 검증을 하고, 이 타입들을 함수에서 사용을 하니 디버깅 시간도 줄일 수 있지 않나 생각이되네요. 예를 들어, 에러가 발생했을 때는 어디에서 오류가 났는 지 찾아내는 과정에 많은 시간이 걸립니다. 타입에 대한 테스트를 돌려보고 타입에 대한 에러가 아님을 빠르게 확인할 수 있다면, 로직에 대한 디버깅에 대해서만 집중하면 될 것입니다. 디버깅 시간을 줄일 수 있다는 것은 프로젝트에 큰 도움이 될 수 있다고 생각합니다!

이외에도, 첫 번째 질문의 답변에도 tsd에 대한 경험에 대한 답변에 보충이 될 것 같습니다!

2022-09-28 11:49 UTC, al-bur requested changes
안녕하세요 온스타~ 고생하셨습니다
온스타의 타입 잘 봤습니다. 보면서 많이 배워가네요!!!

로직 보다는 타입에 집중해서 리뷰 남겼습니다😀

아래는 온스타가 남긴 질문들에 대한 답변들입니다.

> 이번 미션에서 test를 진행할때 모든 타입에 대해 감사를 해야겠다라는 생각을 해 allType라는 객체에 proxy를 제외한 모든 타입을 선언하고 테스트에서 순회를 하면서 사용을 했는데, 하고보니 이럴 필요가 있나라는 생각도 들기도하는데, 앨버는 어떻게 보시나요..?

 저도 온스타와 동일한 생각을 가지고 있습니다. 이번에 거의 모든 타입에 대해서 테스트 코드를 작성하고 테스트하였는데요. isNumber, isFunction등과 같이 간단한 타입 같은 경우에는 굳이 테스트 코드까지 작성해가면서 해줄 필요는 없겠다 싶었습니다. (예외 사항이 발생할 가능성도 작고, 한 눈에 타입을 이해하기 쉬워서)

사실, 제가 생각했을 때 테스트라는 것은(TDD가 아니라는 가정) 여러 가지 이유로 진행된다고 생각합니다.

첫 번째는, 검증을 하고자 하는 것(함수, 로직, 타입등)이 복잡해서 예상하기 힘든 상황들을 꼼꼼하게 체크하기 위해서!
ex) 유틸 타입를 테스트하기 위해 거의 모든 경우의 수(input + output)에 대한 테스트 코드를 작성

두 번째는, 리팩토링 과정에서 실수를 방지하고, 리팩토링 속도를 올리기 위해서!
ex) 복잡한 유틸 타입에 대한 리팩토링을 진행할 때마다, 모든 경우의 수를 일일이 체크하기란 쉽지 않습니다. 휴먼 에러가 발생하게 되면 이전에 동작했던 것들도 동작하지 않을 가능성이 큽니다. 그래서 테스트를 통해서 이러한 위험들을 감소시키면서 리팩토링 속도를 올릴 수 있을 것 같습니다.

결론을 말씀드리면, 단순한 타입에 대한 테스트에 대해서는 의문이 들고, 복잡한 타입에 대해서는 테스트를 해주는 것이 안전한 서비스를 만들 수 있는 요소가 될 수 있을 것 같습니다.

> 함수 구현 내부에서 타입가드겸 맞지 않는 타입이 들어왔을 때, throw문으로 에러를 띄울 수 있도록 해놓았는데, 이 경우 tsd 없이도 어느정도 타입 테스트가 진행이 가능했던 것 같습니다. tsd에 대한 필요성을 미션을 진행하면서 잘 느끼지 못했는데, 앨버에게 tsd를 사용한 경험은 어땠나요?

`함수 구현 내부에서 타입가드겸 맞지 않는 타입이 들어왔을 때, throw문으로 에러를 띄울 수 있도록 해놓았는데, 이 경우 tsd 없이도 어느정도 타입 테스트가 진행이 가능했던 것 같습니다.` 에 대한 혹시 예시를 알려주실 수 있으신가요?!

질문에 대한 답변을 드리는데 더 도움이 될 것 같아서요!!

### tsd 사용 경험
이번에 제가 tsd를 사용한 경험에 대해서 말씀드릴게요

결론부터 말씀드리면, `복잡한 타입을 만들 때는 tsd를 사용해도 좋겠다`입니다.

저는 다음과 같은 흐름의 tdd 방식을 사용해 타입을 정의해주었습니다.
1. 타입에 대한 테스트 작성(테스트 실패)
2. 테스트를 통과하기 위한 타입 선언(테스트 성공)
3. 로직 구현 및 타입 적용

이번 미션에서 pick, omit등과 같이 조금 복잡한 유틸 타입을 처음부터 만드는 것이 조금 막막했었습니다. 근데, tdd 방식을 통해 미리 타입의 input과 output에 대한 테스트 코드들을 작성해보고 하나씩 테스트들을 통과시키기 위해 타입을 작성하다보니 어느덧 원하던 모습의 유틸 함수가 만들어져있었습니다. 이렇게 복잡한 타입을 만드는 데, tsd를 통한 tdd 방식은 꽤 괜찮다고 생각합니다. (단, tdd가 아닐 때는 잘 모르겠네요. 온스타는 어땠나요? 복잡한 타입을 만드는 데 테스트가 도움이 됐나요??)

또한, tsd를 통해 타입에 대해 검증을 하고, 이 타입들을 함수에서 사용을 하니 디버깅 시간도 줄일 수 있지 않나 생각이되네요. 
예를 들어, 에러가 발생하게되면 어디에서 오류가 났는 지 찾아내는 과정은 많은 시간이 필요합니다. 타입에 대한 테스트가 작성이 되어 있다면, 테스트를 돌려보고 타입에 대한 에러가 아님을 빠르게 확인할 수 있다면, 로직에 대한 디버깅에 대해서만 집중하면 될 것입니다. 빠르게 버그의 원인을 추론해볼 수 있으니, 디버깅 시간을 줄일 수 있을 것입니다.

이외에도, `첫 번째 질문의 답변`에도 tsd에 대한 경험에 대한 이야기가 될 수 있을 것 같아 다시 봐주시면 감사하겠습니다!

2022-09-28 11:49 UTC, al-bur commented on __tests__/isFunction.test.ts
> +const value_is_function = function () {},
이게 snakecase인가요??? 스타만의 이유가 있나요?

2022-09-28 11:49 UTC, al-bur commented on src/res/index.ts
> +export const allTypes = {
이렇게 모든 데이터 타입을 모아놓은 객체를 만들어 놓으니 테스트할 때 사용하기 좋겠군요!

2022-09-28 11:49 UTC, al-bur commented on jest.config.js
> +/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
이건 무엇인가요?

2022-09-28 11:49 UTC, al-bur commented on package.json
>  }
꼼꼼한 pacakge.json 이네요~

2022-09-28 11:49 UTC, al-bur commented on src/esm/index.ts
> +export { default as throttle } from '../libs/throttle';
해당 파일의 용도는 뭔가요?

2022-09-28 11:49 UTC, al-bur commented on src/_/index.ts
> +export default _;
```typescript
import Dom from '../utils/dom';
import libs from '../libs';
```

이렇게, 다른 곳에서 import 해서 다시 export 해주고 있는데요. 혹시 이렇게 해주신 이유가 있을까요?

사실 `libs/index.ts`를 통해서 이미 libs 폴더내에 있는 모듈들을 한 번 모아서 export해주고 있어서요!!

2022-09-28 11:49 UTC, al-bur commented on src/libs/index.ts
> +};
왜 한 번에 모아서 내보내주셨나요??

2022-09-28 11:49 UTC, al-bur commented on src/libs/isFunction.ts
> +export default function isFunction<T>(value: T | unknown): value is Function {
value is Function은 boolean과 뭐가 다를까요?

2022-09-28 11:49 UTC, al-bur commented on src/libs/memoize.ts
> +export default function memoize<T extends (...args: any[]) => unknown>(
...args에 대한 타입을 unknown[]이 아닌 any[]로 해주신 이유가 있을까요?

2022-09-28 11:49 UTC, al-bur commented on src/libs/shuffle.ts
> +export default function shuffle<T>(array: readonly T[]): T[] {
readonly 너무 좋네요!

2022-09-28 11:49 UTC, al-bur commented on src/utils/dom.ts
> +    event: string,
event에 대한 타입을 조금 더 제한해 줄 수 있지 않을까요?

2022-09-28 11:49 UTC, al-bur commented on src/utils/getObjectValues.ts
> +export default function getObjectValues<T extends Record<string, any>>(
여기서 any를 사용해준 이유가 있나요?

2022-09-29 01:35 UTC, cks3066 commented on __tests__/isFunction.test.ts
> +const value_is_function = function () {},
value_is_function, value_is_not_function 같은 비슷하지만 완전히 상반된 의미를 가진 변수명을 사용하는데, 
valueIsFunction, valueIsNotFunction 처럼 calmelcase의 경우는 명확히 구분되지 않더라고요..!

저도 js에서는 보통 camelcase를 사용하는데, 해당 변수명에서는 예외적으로 단어들끼리 좀 더 명확한 분리가 되어 읽기 편하게끔하고 싶었습니다.

2022-09-29 01:45 UTC, cks3066 commented on jest.config.js
> +/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
저는 babel을 이용하지않고, jest의 타입스크립트 관련 전처리기인 ts-jest를 이용했는데

`npx ts-jest config:init`

헤당 환경에서 위의 커맨드로 기본 설정파일을 구성할때, 자동으로 형상된 라인입니다.

ts-jest가 ts-jest/dist 에 있는 types 모듈을 바탕으로 타입을 가져오는게 아닐까.. 생각합니다.

2022-09-29 01:52 UTC, cks3066 commented on src/esm/index.ts
> +export { default as throttle } from '../libs/throttle';
해당 미션을 라이비러리로 배포하여 다른 프로젝트에 사용해보는 테스트를 했는데,
이때 트리쉐이킹이 가능하도록 해주는 파일입니다.

빌드 파일의 entry point는 esm/index.js 를 가리키게 되어있고 여기서 기능들을 각각의 모듈로 분리하고있습니다.

`import {_, $, isNull, isFunction} from "onsdash"` 

이렇게 필요한 기능들만 가져올 수 있도록 하려고했습니다!

2022-09-29 02:08 UTC, cks3066 commented on src/_/index.ts
> +export default _;
namespace(기존의 module)의 역할이 필요해서 여기서 다시 export를 해주고있는데요, 

함수에 동일한 이름의 namespace를 이용하면 간단히 병합되는데,  
다른 곳에서 해당 모듈을 사용할때 _() 같은 함수 실행과 _.isNull 같은 메서드의 접근을 허용하기 위해 
해당 파일에서 _ 라는 이름으로 다시 묶어 export 해주고 있습니다.

2022-09-29 03:03 UTC, cks3066 commented on src/libs/index.ts
> +};
`import libs from '../libs';`

_/index.ts 에서 import 문을 한번만 쓰고싶어서 libs 폴더에 있는 파일들은 하나의 파일에서 묶어서 관리하고있습니다..!

namespace 내부에서는  선언 할당이 필요해서 `export { default as omit } from '../libs/omit';` 같은게 안되더라고요..!

2022-09-29 03:10 UTC, cks3066 commented on src/libs/isFunction.ts
> +export default function isFunction<T>(value: T | unknown): value is Function {
타입을 체크하는 함수는 is로 반환값의 타입을 좁히는게 어울리다고 생각을 하는데요.

만약 value is Function이 반환값인 isNull을 이용해서 타입가드를 하게되면, 
인자에 들어온 value에 대한 타입을 Function으로 좁혀준다고해서 사용했습니다..!
그냥 boolean으로만 반환하면 타입가드의 역할만 할 뿐 타입을 좁혀주지는 않을거고요..!

2022-09-29 03:29 UTC, cks3066 commented on src/libs/memoize.ts
> +export default function memoize<T extends (...args: any[]) => unknown>(
내장된 타입 정의에서 arg, argArray 같은 rest 파라미터의 타입들을 any로 관리하는 부분을 보고 저도 any로 사용했습니다..

콜백함수의 인자들 같은 경우는 memoize 함수에서 관여할 사항은 아닌것같아서, any도 어울리지 않을까 생각했는데

unknown이 어울릴까요?

memoize에서 콜백 함수의 인자들과 리턴값에 대한 타입은 조금 더 고민해봐야겠네요..!

2022-09-29 03:38 UTC, cks3066 commented on src/utils/dom.ts
> +    event: string,
우선 해놓고 나중에 다시 봐야지했던건데 놓치고있었네요.. ㅎㅎ
조금 더 고민해볼게요!!

2022-09-29 04:00 UTC, cks3066 commented on src/utils/getObjectValues.ts
> +export default function getObjectValues<T extends Record<string, any>>(
코드 작성시에는 어떤 타입이든 올 수 있지~ 이러면서 큰 생각없이 사용했던것 같은데, 
앨버가 짚어줘서 다시 한번 생각해보니 object의 value로 한정지을 수 있겠더라구요!

`export default function getObjectValues<T extends Record<string, T[keyof T]>>(`

이렇게 수정해봤습니다! 반환 타입도 원래 any[] 가 나왔었는데 value만 모은 배열로 추론되네요!

2022-09-29 04:08 UTC, cks3066 commented
```
isNumber, isFunction등과 같이 간단한 타입 같은 경우에는 굳이 테스트 코드까지 작성해가면서 해줄 필요는 없겠다 싶었습니다. 
(예외 사항이 발생할 가능성도 작고, 한 눈에 타입을 이해하기 쉬워서)

```

맞네요. 로직이 너무 명확하고 쉬운 경우까지 다 테스트하려면 오히려 테스트 코드 작성에 드는 비용이 아까울 수 있겠네요 ㅋㅋㅋㅋ

---

```
첫 번째는, 검증을 하고자 하는 것(함수, 로직, 타입등)이 복잡해서 예상하기 힘든 상황들을 꼼꼼하게 체크하기 위해서!
ex) 유틸 타입를 테스트하기 위해 거의 모든 경우의 수(input + output)에 대한 테스트 코드를 작성

두 번째는, 리팩토링 과정에서 실수를 방지하고, 리팩토링 속도를 올리기 위해서!
ex) 복잡한 유틸 타입에 대한 리팩토링을 진행할 때마다, 모든 경우의 수를 일일이 체크하기란 쉽지 않습니다.
 휴먼 에러가 발생하게 되면 이전에 동작했던 것들도 동작하지 않을 가능성이 큽니다. 
그래서 테스트를 통해서 이러한 위험들을 감소시키면서 리팩토링 속도를 올릴 수 있을 것 같습니다.

결론을 말씀드리면, 단순한 타입에 대한 테스트에 대해서는 의문이 들고, 
복잡하거나 여러 모습으로 변환이 될 수 있는 유틸타입에 대해서는 테스트를 해주는 것이 
안전한 서비스를 만들 수 있는 요소가 될 수 있을 것 같습니다.
```

완전 동의합니다!!

---
```
함수 구현 내부에서 타입가드겸 맞지 않는 타입이 들어왔을 때, 
throw문으로 에러를 띄울 수 있도록 해놓았는데, 이 경우 tsd 없이도 어느정도 타입 테스트가 진행이 가능했던 것 같습니다. 

에 대한 혹시 예시를 알려주실 수 있으신가요?!
```
```js
 if (
    typeof object !== 'object' ||
    Object.prototype.toString.call(object) !== '[object Object]'
  ) {
    throw new Error('pick(object, keys) - object의 타입이 Object가 아닙니다.');
  }
  if (!Array.isArray(keys)) {
    throw new Error('pick(object, keys) - keys의 타입이 Array가 아닙니다.');
  }
```
```js
  test('omit의 object 인자의 타입이 생성된 객체가 아닌 경우, 에러를 반환한다.', () => {
    values_is_not_object.map((value) => {
      expect(() => _.omit(value as any, keys as any)).toThrow(
        'omit(object, keys) - object의 타입이 Object가 아닙니다.'
      );
    });
  });

  test('omit의 keys 인자가 배열이 아닌 경우, 에러를 반환한다.', () => {
    values_is_not_array.map((value) => {
      expect(() => _.omit(values_is_object as any, value as any)).toThrow(
        'omit(object, keys) - keys의 타입이 Array가 아닙니다.'
      );
    });
  });
```




질문에 대한 답변을 드리는데 더 도움이 될 것 같아서요!!

tsd 사용 경험
이번에 제가 tsd를 사용한 경험에 대해서 말씀드릴게요

결론부터 말씀드리면, 복잡한 타입을 만들 때는 tsd를 사용해도 좋겠다입니다.

저는 다음과 같은 흐름의 tdd 방식을 사용해 타입을 정의해주었습니다.

타입에 대한 테스트 작성(테스트 실패)
테스트를 통과하기 위한 타입 선언(테스트 성공)
로직 구현 및 타입 적용
이번 미션에서 pick, omit등과 같이 조금 복잡한 함수에 대한 타입을 처음부터 만드는 것이 조금 막막했었습니다. 근데, tdd 방식을 통해 미리 타입의 input과 output에 대한 테스트 코드들을 작성해보고 하나씩 테스트들을 통과시키기 위해 타입을 작성하다보니 어느덧 원하던 모습의 타입이 만들어져있었습니다. 이렇게 복잡한 타입을 만드는 데, tsd를 통한 tdd 방식은 꽤 괜찮다고 생각합니다. (단, tdd가 아닐 때는 잘 모르겠네요. 온스타는 어땠나요? 복잡한 타입을 만드는 데 테스트가 도움이 됐나요??)

또한, tsd를 통해 타입에 대해 검증을 하고, 이 타입들을 함수에서 사용을 하니 디버깅 시간도 줄일 수 있지 않나 생각이되네요.
예를 들어, 에러가 발생하게되면 어디에서 오류가 났는 지 찾아내는 과정은 많은 시간이 필요합니다. 타입에 대한 테스트가 작성이 되어 있다면, 테스트를 돌려보고 타입에 대한 에러가 아님을 빠르게 확인할 수 있다면, 로직에 대한 디버깅에 대해서만 집중하면 될 것입니다. 빠르게 버그의 원인을 추론해볼 수 있으니, 디버깅 시간을 줄일 수 있을 것입니다.

이외에도, 첫 번째 질문의 답변에도 tsd에 대한 경험에 대한 이야기가 될 수 있을 것 같아 다시 봐주시면 감사하겠습니다!

2022-09-29 04:24 UTC, al-bur commented on __tests__/isFunction.test.ts
> +const value_is_function = function () {},
스타만의 이유가 있어 좋은 것 같아요!!!
이럴때는 snake_case가 조금 더 가독성 있는 것 같네요~

2022-09-29 04:24 UTC, al-bur commented on jest.config.js
> +/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
아하 그런거군요... 저도 있는 지 봐야겠어요ㅎㅎㅎ감사합니다 스타

2022-09-29 04:25 UTC, al-bur commented on src/esm/index.ts
> +export { default as throttle } from '../libs/throttle';
ESmodul을 위한 파일이군요! 한 수 배워갑니다ㅎㅎ설명 감사드려요

2022-09-29 04:34 UTC, al-bur commented on src/_/index.ts
> +export default _;
이 부분은 아직까지 저는 헷갈리더라고요...
스타가 링크 준 거 너무 좋네요!!ㅎㅎ

2022-09-29 07:31 UTC, al-bur commented on src/libs/isFunction.ts
> +export default function isFunction<T>(value: T | unknown): value is Function {
오 타입가드를 위한 리턴타입이네요! 좋네요

2022-09-29 07:33 UTC, al-bur commented on src/libs/memoize.ts
> +export default function memoize<T extends (...args: any[]) => unknown>(
저도 고민해보겠습니다.

근데, unknown 타입으로 대체할 수 있다면 써주는 게 좋을 것 같아요!

any는 최상위와 최하위 둘 다 가능한 타입이니까요

2022-09-29 07:33 UTC, al-bur commented on src/utils/dom.ts
> +    event: string,
좋습니다

2022-09-29 07:36 UTC, al-bur commented on src/utils/getObjectValues.ts
> +export default function getObjectValues<T extends Record<string, any>>(
좋네요!!

2022-09-29 07:40 UTC, al-bur commented
> 아래가 코드입니다..! 들어오는 인자에 대한 타입을 기반으로 에러를 띄워서 테스트 코드에 작성을 했었는데, 이것도 일종의 타입 테스트가 아닐까..? 라는 생각을 했었습니다..

타입에 대한 테스트라고도 할 수 있을 것 같습니다. 근데, 이것은 런타임때 타입 체크를 해주는 역할일 것 같아서, tsd를 통한 테스트와는 차이가 있을 것 같아요. 

어떻게 생각하나요?

2022-09-29 09:32 UTC, cks3066 commented
> > 아래가 코드입니다..! 들어오는 인자에 대한 타입을 기반으로 에러를 띄워서 테스트 코드에 작성을 했었는데, 이것도 일종의 타입 테스트가 아닐까..? 라는 생각을 했었습니다..
> 
> 타입에 대한 테스트라고도 할 수 있을 것 같습니다. 근데, 이것은 런타임때 타입 체크를 해주는 역할일 것 같아서, tsd를 통한 테스트와는 차이가 있을 것 같아요.
> 
> 어떻게 생각하나요?

타입 테스트이지만 tsd의 성격과는 다른 테스트라는 말이 맞는거같아요.
앨버 덕분에 tsd를 이용한 타입 테스트에 대해 조금 더 명확해졌네요! 감사합니다

2022-09-29 09:35 UTC, onschan commented on src/utils/dom.ts
> +    event: string,
`keyof HTMLElementEventMap`
으로 타입 수정했습니다!

2022-09-29 09:38 UTC, onschan commented on src/libs/memoize.ts
> +export default function memoize<T extends (...args: any[]) => unknown>(
unknown을 사용해도 지장없을때는 any를 지양하는 편이 좋을 수 있다는거죵?
앨버 의견에 동의하구 수정했습니다!

2022-09-29 09:44 UTC, al-bur commented on src/libs/memoize.ts
> +export default function memoize<T extends (...args: any[]) => unknown>(
네네 근데, 타입이 계획한대로 동작하는 데는 저도 확실치 않아서 확인해봐야할 것 같아요!!

2022-09-29 09:44 UTC, al-bur approved these changes
고생했습니다 스타~

2022-09-29 09:55 UTC, merged