[TypeScript & Module Typing] 민초(홍영민) 미션 제출합니다.
woowacourse/ts-module pull request #23
Opened 2022-09-27 13:46 UTC by jswith

## 🔥 팀 미션 적용 결과

본 미션을 수행하며 경험, 영감, 학습한 내용을 팀 미션에 전파해주세요.

- [x] 실제 코드 반영 후 팀 프로젝트에서 타입 테스트 진행
- [x] 자주 사용되는 타입을 유틸로 출시하여 분리

## ✅ 요구사항 구현 확인

> 필히 테스트 & 타입이 포함

### DOM 유틸

- [x] innerHTML()
- [x] show()
- [x] hidden()
- [x] addEvent()

### 유틸

- [x] fetch()
- [x] isNull()
- [x] isNil()
- [x] isNumber()
- [x] isFunction()
- [x] shuffle()
- [x] pick()
- [x] omit()
- [x] memoize()
- [x] debounce()
- [x] throttle()
- [x] clickOutside()

## 🧐 공유

/_ 작업하면서 든 생각, 질문, 새롭게 학습하거나 시도해본 내용 등등 공유할 사항이 있다면 자유롭게 적어주세요 _/
작성중

2022-09-28 03:08 UTC, jhy979 requested changes
오~ 민초 꼼꼼하게 타입 테스트를 진행하시고 구현하셔서 너무 잘 봤습니다✨✨

또 F12 팀에서 유틸 타입을 적용하신 부분들도 굉장히 인상적인데요!

유틸 타입을 적용하여 의도하지 않은 에러를 발견하셨다니 뿌듯하셨을 것 같아요..ㅎㅎ (저는 npm 출시만 해도 뿌듯하더라구요😙)

미션 코드에 대한 피드백은 코멘트로 달아두었어요 민초~

---

👏 PR에 남겨주신 의견들에 대해서 저의 생각을 약간 적어보겠습니다

### 프로젝트 유틸 타입 적용
```ts
export declare type DataFetchStatus = {
  isLoading: boolean;
  isReady: boolean;
  isError: boolean;
};

export declare type ValueOf<T> = T[keyof T];
```
이 부분인데요! 타입을 조금 더 줄일 수 있지 않을까 싶어요. (제가 잘못 이해한 것일 수도 있어요)

✔ 생각
현재는 `isLoading, isReady, isError`가 모두 boolean으로 되어있는데요,
isReady가 true일 때 isError가 true인 경우는 없을 것 같아요. 
하지만 현재는 그런 경우에 대해서도 다 허용이 될 것 같아요.

🤔 하지만 이건 또 너무 과한 타입 내로잉?이 아닌가라는 생각도 드네요. 민초 생각은 어떠신가요?

### npm에 타입 출시 방법

저희 달록팀도 F12팀과 거의 흡사합니다!

처음에는 아무 설정없이 바로 npm 출시를 진행하여 모든 파일들이 포함되어 있었는데요

✔ 프로젝트에 설치된 다른 라이브러리들을 살펴보니 모든 파일을 포함하지 않더라구요.

🔨 그래서 저희는 

1. `index.ts`에 타입 작성
2. tsc 컴파일을 통해 `index.d.ts 와 index.js` 생성
3. `package.json`의 main과 file 옵션을 통해 `index.d.ts, index.js, README.md, package.json`만을 npm에 출시했습니다.

그런데 `d.ts`에 declare global로 설정해주셨는데 그러면 매번 import할 필요없이 사용할  수 있지 않나요?

`타입을 반드시 import해서 사용해야하는 점이 불편했는데`  -> 이 부분을 잘 이해하지 못했어요

2022-09-28 03:08 UTC, jhy979 commented on src/index.ts
> +function _(selector: string): HTMLElement | null {
😀 아래에서 null일 경우 `throw new Error`를 해주셨는데 그렇다면 return 값이 null인 경우는 없지 않나요?

2022-09-28 03:08 UTC, jhy979 commented on src/index.ts
> +    element.innerHTML = str || "";
😀 개인적인 의견인데 str이 undefined일 경우에는 innerHTML 내부의 내용을 빈값으로 대체하기 보다는 기존의 내용을 그대로 유지하는 것은 어떨까요?!

2022-09-28 03:08 UTC, jhy979 commented on src/index.ts
> +  element.addEvent = addEvent;
아 이렇게 메서드 네이밍을 변경하여 (`innerHTML` -> `setInnerHTML`) 기존의 메서드는 유지하고 새로운 메서드를 element에 추가해주셨군요!

이렇게 작성하셔서 return 값에 온전한 Elemente가 들어가게 되었네요. 좋은 방식이네요👍👍👍

2022-09-28 03:08 UTC, jhy979 commented on jest.config.ts
> +  testPathIgnorePatterns: ["__tests__/type.test.ts"],
```js
  testPathIgnorePatterns: ["__tests__/type.test.ts"],
```
✋ 이렇게 작성하시면 `type.test.ts`는 어떻게 테스트할 수 있나요? tsd 명령어를 통해서 테스트하시는건가요?

2022-09-28 03:08 UTC, jhy979 commented on src/index.ts
> +  >(obj: T, array: K[]): Record<string | number, unknown> {
✋ return 값을 제네릭을 사용하여 더 줄일 수 있을까요?

뭔가 더 할 수 있지 않을까 싶은데 저는 생각이 안 나긴하네요..ㅎㅎ

2022-09-28 03:08 UTC, jhy979 commented on src/index.ts
> +    for (const key of array) {
✋ obj의 key값을 순회해야하지 않나요?

2022-09-28 03:08 UTC, jhy979 commented on src/index.ts
> +    let timeout: ReturnType<typeof setTimeout>;
👍 오 이렇게 `ReturnType`으로 설정하는 방식도 좋네요. 저는 늘 구현체로 타고 들어가서 작성했었는데 이렇게 작성하는 것도 좋은 것 같아요!

2022-09-28 03:08 UTC, jhy979 commented on src/index.ts
> +      if (target.isSameNode(event.target)) {
👍 와 `isSameNode`라는 메서드가 있었군요? 좋네요!

2022-09-28 03:08 UTC, jhy979 commented on tsconfig.json
> +    "allowJs": true,
✋ js 파일이 없는데 allowJs를 true로 설정하신 이유가 있을까요?

2022-09-28 03:08 UTC, jhy979 commented on __tests__/api.test.ts
> +import _ from "../src";
😀 test가 전부 깔끔하네요!

2022-09-28 03:08 UTC, jhy979 commented on __tests__/type.test.ts
> +);
😀 이야 타입 테스트를 모든 구현에 대해서 진행하셨네요 멋집니다...!

2022-09-28 03:17 UTC, jhy979 commented on src/index.ts
> +  }
```suggestion
  export function isNull(value: unknown): boolean {
    return value === null;
  }
```

민초 궁금한게 있는데 이렇게 제네릭을 사용하지 않은 것과는 차이가 있나요?

2022-09-28 03:24 UTC, jswith commented
> 그런데 d.ts에 declare global로 설정해주셨는데 그러면 매번 import할 필요없이 사용할 수 있지 않나요?

import해서 별도의 파일에 global declare 하는 것이 불편하다는 의미였습니다! tsconfig 설정을 통해 node_modules에 있는 파일을 바로 타입으로 인식하는 방법은 없을까 궁금합니다!

2022-09-28 07:59 UTC, jswith commented on jest.config.ts
> +  testPathIgnorePatterns: ["__tests__/type.test.ts"],
🎤 type에 관한 테스트는 tsd로 테스트하고, api에 대한 테스트는 jest로 테스트하기 위해서 설정해두었습니다!

2022-09-28 08:00 UTC, jswith commented on src/index.ts
> +  element.addEvent = addEvent;
👍🏻

2022-09-28 08:01 UTC, jswith commented on src/index.ts
> +    for (const key of array) {
🎤 배열의 value 값을 순회해서 원하는 요소를 omit하는 코드입니다! 
```typescript
d
```

2022-09-28 08:03 UTC, jswith commented on src/index.ts
> +      if (target.isSameNode(event.target)) {
👍🏻

2022-09-28 08:03 UTC, jswith commented on src/index.ts
> +    let timeout: ReturnType<typeof setTimeout>;
👍🏻

2022-09-28 08:03 UTC, jswith commented on __tests__/api.test.ts
> +import _ from "../src";
👍🏻

2022-09-28 08:03 UTC, jswith commented on __tests__/type.test.ts
> +);
👍🏻

2022-09-28 08:06 UTC, jswith commented on tsconfig.json
> +    "allowJs": true,
복붙하고 소거하는 과정에서 남겨둔 것 같아요 🫣

2022-09-28 08:10 UTC, jswith commented on tsconfig.json
> +    "allowJs": true,
[677c7cf](https://github.com/woowacourse/ts-module/pull/23/commits/677c7cf747383d307649ffc2a2b2bc228b7e201d)

2022-09-28 08:13 UTC, jswith commented on src/index.ts
> +    for (const key of array) {
🎤 오 예리하시네요!! 수정하겠습니다

2022-09-28 08:20 UTC, jswith commented on src/index.ts
> +    element.innerHTML = str || "";
나인의 생각도 좋은 방법인 것 같아요! 👍🏻
저는 빈 매개변수일 경우에는 내부를 비워준다는 생각으로 구현했습니다!

2022-09-28 08:22 UTC, jswith commented on src/index.ts
> +function _(selector: string): HTMLElement | null {
🎤 오 예리하시네요!! 수정하겠습니다

2022-09-28 08:26 UTC, jswith commented on src/index.ts
> +    for (const key of array) {
[fc6cbc5](https://github.com/woowacourse/ts-module/pull/23/commits/fc6cbc5545bfbc6e2e61c5b69552e891080093e9)

2022-09-28 08:26 UTC, jswith commented on src/index.ts
> +function _(selector: string): HTMLElement | null {
[050ae9d](https://github.com/woowacourse/ts-module/pull/23/commits/050ae9da7a3d8c13a7ec4b46ea9c33c2b8396cdd)

2022-09-28 08:49 UTC, jswith commented on src/index.ts
> +  >(obj: T, array: K[]): Record<string | number, unknown> {
이것저것 시도해보았는데,
tsd에서 `Parameter type Record<string | number, unknown> is declared too wide for argument type` 오류를 뱉어서
저도 당장은 생각나지가 않네요! 😂

2022-09-28 08:55 UTC, jswith commented on src/index.ts
> +  }
https://stackoverflow.com/questions/71502196/what-difference-between-extends-and-in-generic-types

2022-09-28 09:06 UTC, jswith commented on src/index.ts
> +  }
글쎄요 🤣 현재 상황에서는 뭐가 다른지 저도 잘 모르겠어요 ㅠ 제네릭이 좀 더 간지나긴하네용

2022-09-29 03:10 UTC, jhy979 commented on src/index.ts
> +  >(obj: T, array: K[]): Record<string | number, unknown> {
저두용... 혹시 제가 적용한다면 답변 다시 달겠습니다 ㅎㅎ

2022-09-29 03:13 UTC, jhy979 commented on src/index.ts
> +  }
ㅋㅋㅋ간지는 제네릭이 짱이긴하죠. 이게 진짜 ts다!

2022-09-29 03:14 UTC, jhy979 commented
역시 민초😝😝

제가 달았던 코멘트들에 대해서 빠르게 적용을 해주셨군요! 바로 머지하겠습니다.

앞으로도 ts를 더 잘 쓸 수 있도록 함께 달려봅시다!

2022-09-29 03:14 UTC, merged